name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt5 tensorflow pillow scipy numpy tqdm
    
    - name: Train initial model if needed
      run: |
        if (-not (Test-Path -Path "digit_model.keras")) {
          python train_model.py
        }
    
    - name: Build digit_recognizer (main app)
      run: |
        pyinstaller --onefile --windowed --name digit_recognizer digit_recognizer.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: digit-recognition-app
        path: |
          dist/
          digit_model.keras
